### ISSUE TITLE
已經比完的熱身賽上面會附註說取消不補賽

### ISSUE THREAD

**Issue by zyu469** [DolphinWing/CpblCalendarProject#3]
2018年熱身賽的部分
可以附註 取消 不補賽嗎 謝謝

**Comment by DolphinWing** [comment]
@zyu469 哈囉~ 目前資料是從官網擷取的，還沒有看到有取消耶，是哪一場有確定的嗎？我看今天才要打第一場比賽，如果他有在官網列出來取消的話，我在看怎麼添加喔。謝謝

**Comment by zyu469** [comment]
不客氣
之前的熱身賽賽程 怎麼會寫取消不補賽呢

DolphinWing <notifications@github.com> 於 2018年3月12日 星期一寫道：

**Comment by DolphinWing** [comment]
應該是官網也有列出取消比賽的吧~ 
先前應該就有實作判斷這個囉，假如有附加訊息的話，比如說取消或延期，會附註在比賽的底下。

**Comment by zyu469** [comment]
明白
之前的每場熱身賽都有附註
今年的會比照辦理嗎

DolphinWing <notifications@github.com> 於 2018年3月12日 星期一寫道：

**Comment by DolphinWing** [comment]
我看到那個 取消不補賽 了！這應該是 bug XDDD
這已經比完了，應該不會有這個才對

**Comment by DolphinWing** [comment]
@zyu469 感謝你的回報，發現了沒注意到的 bug 。下一版 3.0.6 會修正。

**Comment by zyu469** [comment]
對了 熱身賽取消比賽的部分 不要顯示0比0
這樣會以為有比賽
