### ISSUE TITLE
Should not show expired announcements

### ISSUE THREAD

**Issue by DolphinWing** [DolphinWing/CpblCalendarProject#5]

**Comment by zyu469** [comment]
是甚麼原因呢

DolphinWing <notifications@github.com> 於 2018年4月10日 週二 00:40 寫道：

**Comment by DolphinWing** [comment]
判斷式錯誤
https://github.com/DolphinWing/CpblCalendarProject/blob/acd2f244033af16fafb652c8e25ffca5f34efe85/app/src/design/java/dolphin/android/apps/CpblCalendar3/HighlightActivity.java#L309-L311

**Comment by zyu469** [comment]
2011至2016 Lamigo的代表色
怎麼會是灰色


DolphinWing <notifications@github.com> 於 2018年4月12日 週四 09:16 寫道：
