### ISSUE TITLE
CustomTabsIntent.launchUrl ActivityNotFoundException

### ISSUE THREAD

**Issue by DolphinWing** [DolphinWing/CpblCalendarProject#6]
https://stackoverflow.com/questions/34823420/chrome-custom-tabs-throwing-an-error-when-chrome-is-not-installed-no-activity

https://developer.chrome.com/multidevice/android/customtabs#bestpractices

**Comment by zyu469** [comment]
發生什麼問題

DolphinWing <notifications@github.com> 於 2018年4月14日 週六 18:35 寫道：

**Comment by DolphinWing** [comment]
Just some crush reports from Google Play Developer Console
