### ISSUE TITLE
賽程資訊與棒球LOGO有小問題

### ISSUE THREAD

**Issue by zyu469** [DolphinWing/CpblCalendarProject#7]
2005年沒有原定的比賽日期
還有2011-2016年的Lamigo桃猿 代表色不是灰色 是靛藍色

**Comment by DolphinWing** [comment]
那個 logo 顏色都是從該年的隊伍 logo 中取出來的，我不知道為什麼會有你說的顏色不對的問題。

2005年的官網資料有錯，所以沒有顯示出來。我已經手動修改了。

**Comment by zyu469** [comment]
手動修改哪部分
我看的時候是淡灰色

DolphinWing <notifications@github.com> 於 2018年4月24日 週二 23:15 寫道：

**Comment by DolphinWing** [comment]
顏色的部份，下次會修正回之前的樣子。

手動修正是補賽的參考資料，那些資料保留在雲端。因為平常沒有人會查詢那麼舊的比賽資料，所以沒有包含在APP中。到進階設定內去清空本機資料後，會重新抓取雲端的參考日期，就會顯示原本的比賽日期。

**Comment by zyu469** [comment]
了解
之前的樣子 是怎麼樣呢

DolphinWing <notifications@github.com> 於 2018年4月26日 週四 10:14 寫道：

**Comment by zyu469** [comment]
2011-16年 Lamigo的棒球Logo顏色 改回原來的深藍色了

2011-16的部分 Lamigo是那一種為主要顏色

**Comment by zyu469** [comment]
2011至16年的Lamigo的棒球logo 怎麼會是深藍色

**Comment by zyu469** [comment]
對了 為什麼2011-16年 Lamigo的代表色 會改回原先的顏色呢
